### ISSUE TITLE
additional_field doesn't appear to work

### ISSUE THREAD

**Issue by glademiller** [hlb8122/tracing-gelf#2]
I am using aditional_field on the builder to add a field name "service" that contains a string value. Logs are showing up in Graylog but the additional field doesn't appear and other fields being added in my events apart from the message field are also appear to not be sent to Graylog. This is my initialization code:
```rust
tracing_gelf::Logger::builder().additional_field("service", "service_name").init_udp(addr)
```

**Comment by hlb8122** [comment]
Will look into it later tonight. Thank you.

**Comment by hlb8122** [comment]
@glademiller ok, `additional_field` in the builder should now correctly add the persistent additional fields to the logger with `v0.2.2`. Also snuck a tiny optimization in there too.

Get back to me on whether this has solved your problems :)

**Comment by glademiller** [comment]
Thank you for the quick response on this @hlb8122 it does appear to be working I see the fields in Graylog. That said it looks like the additional_field is being sent over quotes in all so in this case instead of the field service having **service_name** in the value in graylog it contains **"service_name"** quotes and all.

**Comment by hlb8122** [comment]
@glademiller Ah thanks. [GELF](https://docs.graylog.org/en/3.2/pages/gelf.html) requires that the additional fields are either a string or a number, the conversion I wrote did some weird stuff when coercing from string -> string - seems to be fixed now in v0.2.3.

Again, get back to me if it's all good now and we can get this closed.

**Comment by glademiller** [comment]
Works like a charm thank you!

**Comment by hlb8122** [comment]
@glademiller Glad to hear it. Any other hiccups or feature requests, fire them my way!
