### ISSUE TITLE
Changing the host/source field

### ISSUE THREAD

**Issue by silmeth** [hlb8122/tracing-gelf#22]
The library adds the `host` field by default to `hostname::get()?` value which then is by default used by Graylog as the source of the message – is there any way to customize it, set the value to something else?

**Comment by hlb8122** [comment]
Not currently, but it should be very easy to add it - we just need to add another setter to the builder and default to the existing behaviour.

**Comment by silmeth** [comment]
Thanks for so quick reply!

Are you willing to do this? Or should I contribute a PR?
