### ISSUE TITLE
Fields from Spans not sent to Graylog

### ISSUE THREAD

**Issue by glademiller** [hlb8122/tracing-gelf#3]
Thanks again for all your help on this. I was looking through the code and it looks like as things are setup today the fields that are added to spans that are in context are not reported. This is one of the main reasons I picked up tracing for my logging so I would love for those to propagate all the way out to Graylog as well.

**Comment by glademiller** [comment]
I attempted to see if I could spot the problem but with no luck. This very well could be me doing something wrong. To add context I have a futures that I am instrumenting and what I expect is every event within that future to log with the fields from the span I used to instrument it.

**Comment by glademiller** [comment]
I think I see what is happening the Layer implementation for Logger doesn't handle new_span and on_record which would be needed to record this information.

**Comment by glademiller** [comment]
I opened https://github.com/hlb8122/tracing-gelf/pull/4 based heavily on this file for the format layer https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/src/fmt/fmt_layer.rs

**Comment by hlb8122** [comment]
@glademiller Thanks! Will check this over the weekend.

**Comment by glademiller** [comment]
@hlb8122  I tested this branch on my staging environment and it is working as expected.
