### ISSUE TITLE
`TRACE` & `DEBUG` priority swapped in GELF payload

### ISSUE THREAD

**Issue by overhacked** [hlb8122/tracing-gelf#5]
`TRACE` should be a lower priority message than `DEBUG`, but in the GELF payload:
https://github.com/hlb8122/tracing-gelf/blob/03373511c99668021401c6e7d4abf819dddb00cf/src/lib.rs#L436-L437

Is there a use case that I don't understand? I'll submit a small PR to change this but let me know if there's something I don't see.

**Comment by overhacked** [comment]
Proposed change in PR #6.

**Comment by hlb8122** [comment]
@overhacked Published `0.4` which fixes this bug.
